# Generated by Django 2.2.4 on 2021-02-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoNinjaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
